Import module fix (#82)
* allow import module command to import all submodules too

* hhnk research tools as package instead of editable install

* update lock and exclude .pixi in search

* get __version__ from pyproject

* fix pytests not running

fixes: TypeError: __call__() got an unexpected keyword argument 'wrapper'

* update project name

* rename hrt import

wasnt working on gh action

* revert project name change

* restore editable install

---------

Co-authored-by: wvangerwen <41104904+wvangerwen@users.noreply.github.com>